name: test

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-1
          restore-keys: |
            go-
      - run: ls -R ~/go/pkg/mod ~/.cache/go-build || true
      - run: go env
      - run: go build
      - run: GOBIN=$(pwd)/bin go install honnef.co/go/tools/cmd/staticcheck@latest
